#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/lge/mcaymanlm

PRODUCT_COPY_FILES += \
    vendor/lge/mcaymanlm/proprietary/system_ext/etc/init/hw/init.aee.rc:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/init/hw/init.aee.rc \
    vendor/lge/mcaymanlm/proprietary/system_ext/etc/init/init.lge.ims.rc:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/init/init.lge.ims.rc \
    vendor/lge/mcaymanlm/proprietary/vendor/app/mcRegistry/020f0000000000000000000000000000.drbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/020f0000000000000000000000000000.drbin \
    vendor/lge/mcaymanlm/proprietary/vendor/app/mcRegistry/020f0000000000000000000000000000.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/020f0000000000000000000000000000.tlbin \
    vendor/lge/mcaymanlm/proprietary/vendor/app/mcRegistry/030c0000000000000000000000000000.drbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/030c0000000000000000000000000000.drbin \
    vendor/lge/mcaymanlm/proprietary/vendor/app/mcRegistry/030c0000000000000000000000000000.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/030c0000000000000000000000000000.tlbin \
    vendor/lge/mcaymanlm/proprietary/vendor/app/mcRegistry/031c0000000000000000000000000000.drbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/031c0000000000000000000000000000.drbin \
    vendor/lge/mcaymanlm/proprietary/vendor/app/mcRegistry/031c0000000000000000000000000000.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/031c0000000000000000000000000000.tlbin \
    vendor/lge/mcaymanlm/proprietary/vendor/app/mcRegistry/05120000000000000000000000000000.drbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/05120000000000000000000000000000.drbin \
    vendor/lge/mcaymanlm/proprietary/vendor/app/mcRegistry/05120000000000000000000000000000.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/05120000000000000000000000000000.tlbin \
    vendor/lge/mcaymanlm/proprietary/vendor/app/mcRegistry/05120000000000000000000000000001.drbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/05120000000000000000000000000001.drbin \
    vendor/lge/mcaymanlm/proprietary/vendor/app/mcRegistry/05120000000000000000000000000001.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/05120000000000000000000000000001.tlbin \
    vendor/lge/mcaymanlm/proprietary/vendor/app/mcRegistry/06090000000000000000000000000000.drbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/06090000000000000000000000000000.drbin \
    vendor/lge/mcaymanlm/proprietary/vendor/app/mcRegistry/06090000000000000000000000000000.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/06090000000000000000000000000000.tlbin \
    vendor/lge/mcaymanlm/proprietary/vendor/app/mcRegistry/07010000000000000000000000000000.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/07010000000000000000000000000000.tlbin \
    vendor/lge/mcaymanlm/proprietary/vendor/app/mcRegistry/0706000000000000000000000000004d.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/0706000000000000000000000000004d.tlbin \
    vendor/lge/mcaymanlm/proprietary/vendor/app/mcRegistry/07061000000000000000000000000000.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/07061000000000000000000000000000.tlbin \
    vendor/lge/mcaymanlm/proprietary/vendor/app/mcRegistry/07150000000000000000000000000000.drbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/07150000000000000000000000000000.drbin \
    vendor/lge/mcaymanlm/proprietary/vendor/app/mcRegistry/07150000000000000000000000000000.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/07150000000000000000000000000000.tlbin \
    vendor/lge/mcaymanlm/proprietary/vendor/app/mcRegistry/07170000000000000000000000000000.drbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/07170000000000000000000000000000.drbin \
    vendor/lge/mcaymanlm/proprietary/vendor/app/mcRegistry/07170000000000000000000000000000.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/07170000000000000000000000000000.tlbin \
    vendor/lge/mcaymanlm/proprietary/vendor/app/mcRegistry/08030000000000000000000000000000.tabin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/08030000000000000000000000000000.tabin \
    vendor/lge/mcaymanlm/proprietary/vendor/app/mcRegistry/08040000000000000000000000003419.tabin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/08040000000000000000000000003419.tabin \
    vendor/lge/mcaymanlm/proprietary/vendor/app/mcRegistry/08050000000000000000000000003419.drbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/08050000000000000000000000003419.drbin \
    vendor/lge/mcaymanlm/proprietary/vendor/app/mcRegistry/08050000000000000000000000003419.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/08050000000000000000000000003419.tlbin \
    vendor/lge/mcaymanlm/proprietary/vendor/app/mcRegistry/08080000000000000000000000000000.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/08080000000000000000000000000000.tlbin \
    vendor/lge/mcaymanlm/proprietary/vendor/app/mcRegistry/08110000000000000000000000000000.tabin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/08110000000000000000000000000000.tabin \
    vendor/lge/mcaymanlm/proprietary/vendor/app/mcRegistry/08880000000000000000000000000000.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/08880000000000000000000000000000.tlbin \
    vendor/lge/mcaymanlm/proprietary/vendor/app/mcRegistry/08881000000000000000000000000000.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/08881000000000000000000000000000.tlbin \
    vendor/lge/mcaymanlm/proprietary/vendor/app/mcRegistry/08882000000000000000000000000000.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/08882000000000000000000000000000.tlbin \
    vendor/lge/mcaymanlm/proprietary/vendor/app/mcRegistry/09180000000000000000000000000000.tabin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/09180000000000000000000000000000.tabin \
    vendor/lge/mcaymanlm/proprietary/vendor/app/mcRegistry/09190000000000000000000000000000.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/09190000000000000000000000000000.tlbin \
    vendor/lge/mcaymanlm/proprietary/vendor/app/mcRegistry/40188311faf343488db888ad39496f9a.drbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/40188311faf343488db888ad39496f9a.drbin \
    vendor/lge/mcaymanlm/proprietary/vendor/app/mcRegistry/40188311faf343488db888ad39496f9a.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/40188311faf343488db888ad39496f9a.tlbin \
    vendor/lge/mcaymanlm/proprietary/vendor/app/mcRegistry/5020170115e016302017012521300000.drbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/5020170115e016302017012521300000.drbin \
    vendor/lge/mcaymanlm/proprietary/vendor/app/mcRegistry/5020170115e016302017012521300000.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/5020170115e016302017012521300000.tlbin \
    vendor/lge/mcaymanlm/proprietary/vendor/app/mcRegistry/6b3f5fa0f8cf55a7be2582587d62d63a.drbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/6b3f5fa0f8cf55a7be2582587d62d63a.drbin \
    vendor/lge/mcaymanlm/proprietary/vendor/app/mcRegistry/6b3f5fa0f8cf55a7be2582587d62d63a.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/6b3f5fa0f8cf55a7be2582587d62d63a.tlbin \
    vendor/lge/mcaymanlm/proprietary/vendor/app/mcRegistry/9073f03a9618383bb1856eb3f990babd.drbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/9073f03a9618383bb1856eb3f990babd.drbin \
    vendor/lge/mcaymanlm/proprietary/vendor/app/mcRegistry/9073f03a9618383bb1856eb3f990babd.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/9073f03a9618383bb1856eb3f990babd.tlbin \
    vendor/lge/mcaymanlm/proprietary/vendor/app/mcRegistry/98fb95bcb4bf42d26473eae48690d7ea.tabin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/98fb95bcb4bf42d26473eae48690d7ea.tabin \
    vendor/lge/mcaymanlm/proprietary/vendor/app/mcRegistry/abcd270ea5c44c58bcd3384a2fa2539e.tabin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/abcd270ea5c44c58bcd3384a2fa2539e.tabin \
    vendor/lge/mcaymanlm/proprietary/vendor/app/mcRegistry/e97c270ea5c44c58bcd3384a2fa2539e.tabin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/e97c270ea5c44c58bcd3384a2fa2539e.tabin \
    vendor/lge/mcaymanlm/proprietary/vendor/app/mcRegistry/ffffffff000000000000000000000003.tabin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/ffffffff000000000000000000000003.tabin \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/.tp/dex2oat.conf:$(TARGET_COPY_OUT_VENDOR)/etc/.tp/dex2oat.conf \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/.tp/ds.conf:$(TARGET_COPY_OUT_VENDOR)/etc/.tp/ds.conf \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/.tp/game.conf:$(TARGET_COPY_OUT_VENDOR)/etc/.tp/game.conf \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/.tp/thermal.conf:$(TARGET_COPY_OUT_VENDOR)/etc/.tp/thermal.conf \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/.tp/thermal.off.conf:$(TARGET_COPY_OUT_VENDOR)/etc/.tp/thermal.off.conf \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/audio_device.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_device.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/audio_em.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_em.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/audio_param/AudioFeatureControl_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/AudioFeatureControl_AudioParam.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/audio_param/AudioFeatureControl_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/AudioFeatureControl_ParamUnitDesc.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/audio_param/AudioParamOptions.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/AudioParamOptions.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/audio_param/AudioParamOptions_vext.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/AudioParamOptions_vext.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/audio_param/BtInfo_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/BtInfo_AudioParam.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/audio_param/BtInfo_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/BtInfo_ParamUnitDesc.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/audio_param/HpImpedance_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/HpImpedance_AudioParam.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/audio_param/HpImpedance_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/HpImpedance_ParamUnitDesc.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/audio_param/MicInfo_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/MicInfo_AudioParam.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/audio_param/MicInfo_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/MicInfo_ParamUnitDesc.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/audio_param/PlaybackACF_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackACF_AudioParam.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/audio_param/PlaybackACF_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackACF_ParamUnitDesc.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/audio_param/PlaybackDRC_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackDRC_AudioParam.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/audio_param/PlaybackDRC_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackDRC_ParamUnitDesc.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/audio_param/PlaybackHCF_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackHCF_AudioParam.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/audio_param/PlaybackHCF_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackHCF_ParamUnitDesc.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/audio_param/PlaybackVolAna_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackVolAna_AudioParam.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/audio_param/PlaybackVolAna_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackVolAna_ParamUnitDesc.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/audio_param/PlaybackVolDigi_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackVolDigi_AudioParam.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/audio_param/PlaybackVolDigi_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackVolDigi_ParamUnitDesc.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/audio_param/PlaybackVolUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackVolUI_AudioParam.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/audio_param/PlaybackVolUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackVolUI_ParamUnitDesc.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/audio_param/Playback_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Playback_AudioParam.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/audio_param/Playback_ParamTreeView.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Playback_ParamTreeView.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/audio_param/Playback_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Playback_ParamUnitDesc.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/audio_param/RecordDMNR_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordDMNR_AudioParam.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/audio_param/RecordDMNR_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordDMNR_ParamUnitDesc.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/audio_param/RecordFIR_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordFIR_AudioParam.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/audio_param/RecordFIR_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordFIR_ParamUnitDesc.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/audio_param/RecordUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordUI_AudioParam.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/audio_param/RecordUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordUI_ParamUnitDesc.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/audio_param/RecordVolUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordVolUI_AudioParam.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/audio_param/RecordVolUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordVolUI_ParamUnitDesc.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/audio_param/RecordVol_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordVol_AudioParam.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/audio_param/RecordVol_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordVol_ParamUnitDesc.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/audio_param/Record_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Record_AudioParam.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/audio_param/Record_ParamTreeView.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Record_ParamTreeView.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/audio_param/Record_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Record_ParamUnitDesc.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/audio_param/RingbackVolUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RingbackVolUI_AudioParam.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/audio_param/RingbackVolUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RingbackVolUI_ParamUnitDesc.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/audio_param/RingbackVol_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RingbackVol_AudioParam.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/audio_param/RingbackVol_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RingbackVol_ParamUnitDesc.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/audio_param/SmartPa_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SmartPa_AudioParam.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/audio_param/SmartPa_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SmartPa_ParamUnitDesc.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/audio_param/SoundEnhancement_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SoundEnhancement_AudioParam.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/audio_param/SoundEnhancement_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SoundEnhancement_ParamUnitDesc.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/audio_param/SpeechDMNR_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechDMNR_AudioParam.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/audio_param/SpeechDMNR_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechDMNR_ParamUnitDesc.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/audio_param/SpeechEchoRef_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechEchoRef_AudioParam.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/audio_param/SpeechEchoRef_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechEchoRef_ParamUnitDesc.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/audio_param/SpeechGeneral_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechGeneral_AudioParam.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/audio_param/SpeechGeneral_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechGeneral_ParamUnitDesc.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/audio_param/SpeechMagiClarity_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechMagiClarity_AudioParam.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/audio_param/SpeechMagiClarity_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechMagiClarity_ParamUnitDesc.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/audio_param/SpeechNetwork_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechNetwork_AudioParam.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/audio_param/SpeechNetwork_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechNetwork_ParamUnitDesc.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/audio_param/SpeechUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechUI_AudioParam.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/audio_param/SpeechUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechUI_ParamUnitDesc.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/audio_param/SpeechVolUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechVolUI_AudioParam.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/audio_param/SpeechVolUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechVolUI_ParamUnitDesc.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/audio_param/SpeechVol_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechVol_AudioParam.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/audio_param/SpeechVol_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechVol_ParamUnitDesc.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/audio_param/Speech_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Speech_AudioParam.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/audio_param/Speech_ParamTreeView.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Speech_ParamTreeView.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/audio_param/Speech_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Speech_ParamUnitDesc.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/audio_param/USBCall_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/USBCall_AudioParam.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/audio_param/USBCall_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/USBCall_ParamUnitDesc.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/audio_param/USBDevice_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/USBDevice_AudioParam.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/audio_param/USBDevice_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/USBDevice_ParamUnitDesc.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/audio_param/Ultrasound_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Ultrasound_AudioParam.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/audio_param/Ultrasound_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Ultrasound_ParamUnitDesc.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/audio_param/UplinkConfiguration_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/UplinkConfiguration_AudioParam.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/audio_param/UplinkConfiguration_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/UplinkConfiguration_ParamUnitDesc.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/audio_param/VOW_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VOW_AudioParam.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/audio_param/VOW_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VOW_ParamUnitDesc.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/audio_param/VoIPDMNR_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPDMNR_AudioParam.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/audio_param/VoIPDMNR_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPDMNR_ParamUnitDesc.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/audio_param/VoIPGeneral_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPGeneral_AudioParam.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/audio_param/VoIPGeneral_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPGeneral_ParamUnitDesc.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/audio_param/VoIPUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPUI_AudioParam.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/audio_param/VoIPUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPUI_ParamUnitDesc.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/audio_param/VoIPVolUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPVolUI_AudioParam.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/audio_param/VoIPVolUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPVolUI_ParamUnitDesc.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/audio_param/VoIPVol_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPVol_AudioParam.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/audio_param/VoIPVol_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPVol_ParamUnitDesc.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/audio_param/VoIP_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIP_AudioParam.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/audio_param/VoIP_ParamTreeView.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIP_ParamTreeView.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/audio_param/VoIP_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIP_ParamUnitDesc.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/audio_param/VoIPv2DMNR_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2DMNR_AudioParam.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/audio_param/VoIPv2DMNR_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2DMNR_ParamUnitDesc.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/audio_param/VoIPv2General_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2General_AudioParam.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/audio_param/VoIPv2General_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2General_ParamUnitDesc.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/audio_param/VoIPv2UI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2UI_AudioParam.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/audio_param/VoIPv2UI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2UI_ParamUnitDesc.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/audio_param/VoIPv2_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2_AudioParam.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/audio_param/VoIPv2_ParamTreeView.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2_ParamTreeView.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/audio_param/VoIPv2_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2_ParamUnitDesc.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/audio_param/VoWDspAec_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWDspAec_AudioParam.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/audio_param/VoWDspAec_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWDspAec_ParamUnitDesc.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/audio_param/VoWEngineFeature_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWEngineFeature_AudioParam.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/audio_param/VoWEngineFeature_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWEngineFeature_ParamUnitDesc.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/audio_param/VoWHwVad_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWHwVad_AudioParam.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/audio_param/VoWHwVad_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWHwVad_ParamUnitDesc.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/audio_param/VoWMicSetting_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWMicSetting_AudioParam.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/audio_param/VoWMicSetting_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWMicSetting_ParamUnitDesc.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/audio_param/VoWVoiceCommand_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWVoiceCommand_AudioParam.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/audio_param/VoWVoiceCommand_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWVoiceCommand_ParamUnitDesc.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/audio_param/VolumeGainMapUL_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VolumeGainMapUL_AudioParam.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/audio_param/VolumeGainMapUL_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VolumeGainMapUL_ParamUnitDesc.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/audio_param/VolumeGainMap_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VolumeGainMap_AudioParam.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/audio_param/VolumeGainMap_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VolumeGainMap_ParamUnitDesc.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/audio_param/Volume_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Volume_AudioParam.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/audio_param/Volume_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Volume_ParamUnitDesc.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/audio_policy_volumes.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_policy_volumes.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/aurisys_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/aurisys_config.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/aurisys_config_hifi3.xml:$(TARGET_COPY_OUT_VENDOR)/etc/aurisys_config_hifi3.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/default_volume_tables.xml:$(TARGET_COPY_OUT_VENDOR)/etc/default_volume_tables.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/ecc_list.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/ecc_list_OP01.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP01.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/ecc_list_OP02.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP02.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/ecc_list_OP09.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP09.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/ecc_list_OP12.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP12.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/ecc_list_OP17.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP17.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/ecc_list_OP18.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP18.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/ecc_list_OP20.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP20.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/ecc_list_OP236.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP236.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/ecc_list_preference.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_preference.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/fstb.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/fstb.cfg \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/gnss/agps_profiles_conf2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/agps_profiles_conf2.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_ACG.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_ACG.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_ATnT_Mexico.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_ATnT_Mexico.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_ATnT_US.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_ATnT_US.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_CT.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_CT.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Claro_Peru.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Claro_Peru.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Entel_Peru.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Entel_Peru.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_KDDI.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_KDDI.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_KT_Korea_Telecom.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_KT_Korea_Telecom.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_LG_Uplus.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_LG_Uplus.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_SK_Telecom.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_SK_Telecom.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_SoftBank.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_SoftBank.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Sprint.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Sprint.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_T-Mobile_US.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_T-Mobile_US.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Test_SIM1.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Test_SIM1.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Test_SIM2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Test_SIM2.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_USC.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_USC.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Verizon_Wireless.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Verizon_Wireless.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Vodafone.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Vodafone.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/init/android.hardware.bluetooth@1.1-service-mediatek.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.bluetooth@1.1-service-mediatek.rc \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/init/android.hardware.drm@1.3-service.widevine.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.drm@1.3-service.widevine.rc \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/init/android.hardware.gnss-service.mediatek.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.gnss-service.mediatek.rc \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/init/android.hardware.graphics.allocator@4.0-service-mediatek.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.graphics.allocator@4.0-service-mediatek.rc \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/init/android.hardware.keymaster@4.1-service.trustonic.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.keymaster@4.1-service.trustonic.rc \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/init/android.hardware.media.c2@1.2-mediatek.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.media.c2@1.2-mediatek.rc \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/init/android.hardware.secure_element@1.2-service-mediatek.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.secure_element@1.2-service-mediatek.rc \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/init/android.hardware.thermal@2.0-service.mtk.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.thermal@2.0-service.mtk.rc \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/init/android.hardware.usb@1.1-service-mediatekv2.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.usb@1.1-service-mediatekv2.rc \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/init/camerahalserver.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/camerahalserver.rc \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/init/fuelgauged_init.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/fuelgauged_init.rc \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/init/fuelgauged_nvram_init.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/fuelgauged_nvram_init.rc \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/init/gsm0710muxd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/gsm0710muxd.rc \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/init/hw/init.connectivity.common.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/hw/init.connectivity.common.rc \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/init/hw/init.connectivity.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/hw/init.connectivity.rc \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/init/hw/init.lge.display.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/hw/init.lge.display.rc \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/init/hw/init.lge.fingerprints.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/hw/init.lge.fingerprints.rc \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/init/hw/init.lge.sensors.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/hw/init.lge.sensors.rc \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/init/hw/init.lge.usb.configfs.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/hw/init.lge.usb.configfs.rc \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/init/hw/init.lge.usb.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/hw/init.lge.usb.rc \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/init/hw/init_conninfra.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/hw/init_conninfra.rc \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/init/init.cccimdinit.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.cccimdinit.rc \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/init/init.cccirpcd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.cccirpcd.rc \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/init/init.lge.power.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.lge.power.rc \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/init/init.lge.vendor.on_boot.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.lge.vendor.on_boot.rc \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/init/init.lge.vendor.on_init.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.lge.vendor.on_init.rc \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/init/init.lge.vendor.on_post_fs.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.lge.vendor.on_post_fs.rc \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/init/init.lge.vendor.on_post_fs_data.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.lge.vendor.on_post_fs_data.rc \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/init/init.lge.vendor.on_property.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.lge.vendor.on_property.rc \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/init/init.lge.vendor.services.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.lge.vendor.services.rc \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/init/init.thermal.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.thermal.rc \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/init/init.thermal_manager.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.thermal_manager.rc \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/init/init.thermalloadalgod.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.thermalloadalgod.rc \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/init/init.wlan_drv.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.wlan_drv.rc \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/init/mtk_agpsd_p.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/mtk_agpsd_p.rc \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/init/mtkrild.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/mtkrild.rc \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/init/muxreport.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/muxreport.rc \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/init/netdagent.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/netdagent.rc \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/init/nvram_daemon.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/nvram_daemon.rc \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/init/tee.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/tee.rc \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/init/tetheroffloadservice.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/tetheroffloadservice.rc \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/init/trustonic.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/trustonic.rc \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/init/vendor.lge.hardware.lgdata@1.1-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.lge.hardware.lgdata@1.1-service.rc \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/init/vendor.lge.hardware.vss_ims@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.lge.hardware.vss_ims@1.0-service.rc \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/init/vendor.mediatek.hardware.keymaster_attestation@1.1-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.mediatek.hardware.keymaster_attestation@1.1-service.rc \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/init/vendor.mediatek.hardware.mms@1.6-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.mediatek.hardware.mms@1.6-service.rc \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/init/vendor.mediatek.hardware.mtkpower@1.0-init.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.mediatek.hardware.mtkpower@1.0-init.rc \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/init/vendor.mediatek.hardware.mtkpower@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.mediatek.hardware.mtkpower@1.0-service.rc \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/init/vendor.mediatek.hardware.nvram@1.1-sevice.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.mediatek.hardware.nvram@1.1-sevice.rc \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/init/vendor.mediatek.hardware.pq@2.2-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.mediatek.hardware.pq@2.2-service.rc \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/init/vendor.trustonic.tee@1.1-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.trustonic.tee@1.1-service.rc \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/init/volte_clientapi_ua.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/volte_clientapi_ua.rc \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/init/volte_rcs_ua.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/volte_rcs_ua.rc \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/init/vpud.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vpud.rc \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/init/wlan_assistant.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/wlan_assistant.rc \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/libnfc-nci.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-nci.conf \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/libnfc-nxp-KR.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-nxp-KR.conf \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/libnfc-nxp-SG.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-nxp-SG.conf \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/libnfc-nxp-US.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-nxp-US.conf \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/libnfc-nxp-hk.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-nxp-hk.conf \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/libnfc-nxp-lg.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-nxp-lg.conf \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/libnfc-nxp.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-nxp.conf \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/media_codecs_lge.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs_lge.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/media_codecs_mediatek_audio.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs_mediatek_audio.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/media_codecs_performance.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs_performance.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/media_profiles_V1_0.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_profiles_V1_0.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/mtk_platform_codecs_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/mtk_platform_codecs_config.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/ph_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ph_config.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/power_app_cfg.xml:$(TARGET_COPY_OUT_VENDOR)/etc/power_app_cfg.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/powercontable.xml:$(TARGET_COPY_OUT_VENDOR)/etc/powercontable.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/powerscntbl.xml:$(TARGET_COPY_OUT_VENDOR)/etc/powerscntbl.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/seccomp_policy/android.hardware.media.c2@1.2-extended-seccomp-policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/android.hardware.media.c2@1.2-extended-seccomp-policy \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/seccomp_policy/android.hardware.media.c2@1.2-mediatek-seccomp-policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/android.hardware.media.c2@1.2-mediatek-seccomp-policy \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/seccomp_policy/mediacodec.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/mediacodec.policy \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/seccomp_policy/mediaextractor.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/mediaextractor.policy \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/seccomp_policy/mediaswcodec.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/mediaswcodec.policy \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/sensors/hals.conf:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/hals.conf \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/slp_conf:$(TARGET_COPY_OUT_VENDOR)/etc/slp_conf \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/smartpa_param/tfa98xx_device.bin:$(TARGET_COPY_OUT_VENDOR)/etc/smartpa_param/tfa98xx_device.bin \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/smartpa_param/tfa98xx_music.bin:$(TARGET_COPY_OUT_VENDOR)/etc/smartpa_param/tfa98xx_music.bin \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/smartpa_param/tfa98xx_ringtone.bin:$(TARGET_COPY_OUT_VENDOR)/etc/smartpa_param/tfa98xx_ringtone.bin \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/smartpa_param/tfa98xx_voice.bin:$(TARGET_COPY_OUT_VENDOR)/etc/smartpa_param/tfa98xx_voice.bin \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/special_pws_channel.xml:$(TARGET_COPY_OUT_VENDOR)/etc/special_pws_channel.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/task_profiles.json:$(TARGET_COPY_OUT_VENDOR)/etc/task_profiles.json \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/usb_audio_accessory_only_policy_configuration.xml:$(TARGET_COPY_OUT_VENDOR)/etc/usb_audio_accessory_only_policy_configuration.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/vendor-apns-conf.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vendor-apns-conf.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/virtual-spn-conf-by-efgid1.xml:$(TARGET_COPY_OUT_VENDOR)/etc/virtual-spn-conf-by-efgid1.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/virtual-spn-conf-by-efpnn.xml:$(TARGET_COPY_OUT_VENDOR)/etc/virtual-spn-conf-by-efpnn.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/virtual-spn-conf-by-efspn.xml:$(TARGET_COPY_OUT_VENDOR)/etc/virtual-spn-conf-by-efspn.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/virtual-spn-conf-by-imsi.xml:$(TARGET_COPY_OUT_VENDOR)/etc/virtual-spn-conf-by-imsi.xml \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/wifi/p2p_supplicant_overlay.conf:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/p2p_supplicant_overlay.conf \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/wifi/wpa_supplicant.conf:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/wpa_supplicant.conf \
    vendor/lge/mcaymanlm/proprietary/vendor/etc/wifi/wpa_supplicant_overlay.conf:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/wpa_supplicant_overlay.conf \
    vendor/lge/mcaymanlm/proprietary/vendor/firmware/BT_FW.cfg:$(TARGET_COPY_OUT_VENDOR)/firmware/BT_FW.cfg \
    vendor/lge/mcaymanlm/proprietary/vendor/firmware/WIFI_RAM_CODE_soc3_0_1_1.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/WIFI_RAM_CODE_soc3_0_1_1.bin \
    vendor/lge/mcaymanlm/proprietary/vendor/firmware/conninfra.cfg:$(TARGET_COPY_OUT_VENDOR)/firmware/conninfra.cfg \
    vendor/lge/mcaymanlm/proprietary/vendor/firmware/fm_cust.cfg:$(TARGET_COPY_OUT_VENDOR)/firmware/fm_cust.cfg \
    vendor/lge/mcaymanlm/proprietary/vendor/firmware/lib3a.ccu:$(TARGET_COPY_OUT_VENDOR)/firmware/lib3a.ccu \
    vendor/lge/mcaymanlm/proprietary/vendor/firmware/libpn557_fw.so:$(TARGET_COPY_OUT_VENDOR)/firmware/libpn557_fw.so \
    vendor/lge/mcaymanlm/proprietary/vendor/firmware/mt6635_fm_v1_coeff.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/mt6635_fm_v1_coeff.bin \
    vendor/lge/mcaymanlm/proprietary/vendor/firmware/mt6635_fm_v1_patch.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/mt6635_fm_v1_patch.bin \
    vendor/lge/mcaymanlm/proprietary/vendor/firmware/soc3_0_patch_wmmcu_1_1_hdr.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc3_0_patch_wmmcu_1_1_hdr.bin \
    vendor/lge/mcaymanlm/proprietary/vendor/firmware/soc3_0_ram_bt_1_1_hdr.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc3_0_ram_bt_1_1_hdr.bin \
    vendor/lge/mcaymanlm/proprietary/vendor/firmware/soc3_0_ram_bt_1a_1_hdr.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc3_0_ram_bt_1a_1_hdr.bin \
    vendor/lge/mcaymanlm/proprietary/vendor/firmware/soc3_0_ram_mcu_1_1_hdr.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc3_0_ram_mcu_1_1_hdr.bin \
    vendor/lge/mcaymanlm/proprietary/vendor/firmware/soc3_0_ram_mcu_1a_1_hdr.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc3_0_ram_mcu_1a_1_hdr.bin \
    vendor/lge/mcaymanlm/proprietary/vendor/firmware/soc3_0_ram_mcu_e1_hdr.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc3_0_ram_mcu_e1_hdr.bin \
    vendor/lge/mcaymanlm/proprietary/vendor/firmware/soc3_0_ram_wifi_1_1_hdr.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc3_0_ram_wifi_1_1_hdr.bin \
    vendor/lge/mcaymanlm/proprietary/vendor/firmware/soc3_0_ram_wmmcu_1_1_hdr.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc3_0_ram_wmmcu_1_1_hdr.bin \
    vendor/lge/mcaymanlm/proprietary/vendor/firmware/tfa98xx.cnt:$(TARGET_COPY_OUT_VENDOR)/firmware/tfa98xx.cnt \
    vendor/lge/mcaymanlm/proprietary/vendor/lib/egl/egl.cfg:$(TARGET_COPY_OUT_VENDOR)/lib/egl/egl.cfg

PRODUCT_PACKAGES += \
    arm.graphics-V1-ndk_platform \
    android.hardware.bluetooth@1.1-impl-mediatek \
    vendor.lge.hardware.vss_ims@1.0-impl \
    vendor.mediatek.hardware.bluetooth.audio@2.2-impl \
    libJpgEncPipe \
    libaedv \
    libbluetooth_audio_session_mediatek \
    libbluetooth_mtk \
    libbluetooth_mtk_pure \
    libbt-vendor \
    libbwc \
    libcapctrl \
    libcustom_nvram \
    libfile_op \
    libhevce_sb.ca7.android \
    libion_mtk \
    libion_ulit \
    libjpeg-alpha-oal_vendor \
    libjpeg-alpha_vendor \
    libladder \
    libmtkcutils \
    libmtkperf_client_vendor \
    libmtkproperty \
    libmtkrillog \
    libnvram \
    libnvram_sec \
    libthha \
    libvcodec_oal \
    libvcodecdrv_header_stub \
    libvpu5 \
    libvssims-impl-mtk \
    libmtk_drvb \
    vendor.lge.hardware.vss_ims@1.0 \
    vendor.mediatek.hardware.audio@6.1 \
    vendor.mediatek.hardware.audio@7.1 \
    vendor.mediatek.hardware.bluetooth.audio@2.1 \
    vendor.mediatek.hardware.bluetooth.audio@2.2 \
    vendor.mediatek.hardware.mms@1.0 \
    vendor.mediatek.hardware.mms@1.1 \
    vendor.mediatek.hardware.mms@1.2 \
    vendor.mediatek.hardware.mms@1.3 \
    vendor.mediatek.hardware.mms@1.4 \
    vendor.mediatek.hardware.mms@1.5 \
    vendor.mediatek.hardware.mms@1.6 \
    vendor.mediatek.hardware.nvram@1.0 \
    vendor.mediatek.hardware.nvram@1.1 \
    audio.primary.mt6885 \
    audio.r_submix.mt6885 \
    libHEVCdec_sa.ca7.android \
    libMtkSpeechEnh \
    lib_iir \
    lib_speech_enh \
    libaudio_param_parser-vnd \
    libaudioclient_aidl_conversion \
    libaudiocompensationfilter_vendor \
    libaudiocompensationfilterc \
    libaudiocomponentengine_vendor \
    libaudiocomponentenginec \
    libaudiocustparam_vendor \
    libaudiodcrflt_vendor \
    libaudiofmtconv \
    libaudiofoundation \
    libaudioloudc \
    libaudioprimarydevicehalifclient \
    libaudiotoolkit_vendor \
    libaurisysdemo \
    libbessound_hd_mtk_vendor \
    libblisrc32_vendor \
    libcvsd_mtk \
    libfgauge_gm30 \
    libh264dec_customize \
    libh264dec_sa.ca7 \
    libh264dec_sd.ca7 \
    libh264dec_se.ca7 \
    libh264enc_sa.ca7 \
    libmp4enc_sa.ca7 \
    libmp4enc_xa.ca7 \
    libmsbc_mtk \
    libmtklimiter_vendor \
    libmtkshifter_vendor \
    libnxp_extamp_intf \
    libnxpsmartpaparser \
    librcs_interface \
    librcs_volte_core \
    librt_extamp_intf \
    libspeech_enh_lib \
    libspeechparser_vendor \
    libthermalalgo \
    libvcodec_utility \
    libvcodecdrv \
    libvp8dec_sa.ca7 \
    libvp8enc_sa.ca7 \
    libvp9dec_sa.ca7 \
    libvpud_vcodec \
    libvt_custom \
    LGDataFeature_vendor \
    libGLES_mali \
    libGLES_meow \
    libMEOW_data \
    libMEOW_gift \
    libMEOW_qt \
    libMEOW_trace \
    hi1634_mipi_raw_IdxMgr \
    hi1634_mipi_raw_tuning \
    android.hardware.gnss-impl-mediatek \
    android.hardware.gnss@2.1-impl-mediatek \
    android.hardware.graphics.allocator@4.0-impl-mediatek \
    android.hardware.graphics.mapper@4.0-impl-mediatek \
    fingerprint.mt6885 \
    gps.default \
    hwcomposer.mt6885 \
    kmsetkey.trustonic \
    libMcGatekeeper \
    libSoftGatekeeper \
    thermal_hal \
    vendor.lge.hardware.cameraex@1.0-impl \
    vendor.mediatek.hardware.camera.atms@1.0-impl \
    vendor.mediatek.hardware.camera.isphal@1.0-impl \
    vendor.mediatek.hardware.camera.lomoeffect@1.0-impl \
    vendor.mediatek.hardware.keymaster_attestation@1.1-impl \
    vendor.mediatek.hardware.mms@1.6-impl \
    vendor.mediatek.hardware.mtkpower@1.2-impl \
    vendor.mediatek.hardware.nvram@1.1-impl \
    vendor.mediatek.hardware.pq@2.13-impl \
    lgdatavendorlib \
    lib.com.lge.elvis \
    lib3a.ae.core \
    lib3a.ae \
    lib3a.ae.stat \
    lib3a.af.assist.models \
    lib3a.af.assist \
    lib3a.af.assist.utils \
    lib3a.af.core \
    lib3a.af \
    lib3a.aishutter.models \
    lib3a.alsflicker \
    lib3a.awb.core \
    lib3a.ccudrv \
    lib3a.ccuif \
    lib3a.custom.ae \
    lib3a.dce \
    lib3a.flash \
    lib3a.flicker \
    lib3a.gma \
    lib3a.lce \
    lib3a.log \
    lib3a.n3d3a \
    lib3a.sensors.color \
    lib3a.sensors.flicker \
    libCamera_hi1634mipiraw_AI_Auto \
    libCamera_hi1634mipiraw_AI_Auto_HDR \
    libCamera_hi1634mipiraw_AI_Flower \
    libCamera_hi1634mipiraw_AI_Flower_HDR \
    libCamera_hi1634mipiraw_AI_NightView \
    libCamera_hi1634mipiraw_AI_NightView_HDR \
    libCamera_hi1634mipiraw_AI_People \
    libCamera_hi1634mipiraw_AI_People_HDR \
    libCamera_hi1634mipiraw_AI_Sky \
    libCamera_hi1634mipiraw_AI_Sky_HDR \
    libCamera_hi1634mipiraw_AI_Snow \
    libCamera_hi1634mipiraw_AI_Snow_HDR \
    libCamera_hi1634mipiraw_AI_Text \
    libCamera_hi1634mipiraw_AI_Text_HDR \
    libCamera_hi1634mipiraw_E2EHDR_Preview \
    libCamera_hi1634mipiraw_E2EHDR_Video \
    libCamera_hi1634mipiraw_Face_Capture \
    libCamera_hi1634mipiraw_Flash_Capture \
    libCamera_hi1634mipiraw_HDR_Capture \
    libCamera_hi1634mipiraw_HDR_Preview \
    libCamera_hi1634mipiraw_HDR_Video \
    libCamera_hi1634mipiraw_N3D_Capture \
    libCamera_hi1634mipiraw_N3D_Preview \
    libCamera_hi1634mipiraw_N3D_Video \
    libCamera_hi1634mipiraw_Outfocus_Capture \
    libCamera_hi1634mipiraw_P1_YUV \
    libCamera_hi1634mipiraw_Panorama \
    libCamera_hi1634mipiraw_Scene_Capture \
    libCamera_hi1634mipiraw_Scene_Capture_4cell \
    libCamera_hi1634mipiraw_Scene_Capture_HDR \
    libCamera_hi1634mipiraw_Scene_Preview \
    libCamera_hi1634mipiraw_Scene_Preview_4k \
    libCamera_hi1634mipiraw_Scene_Preview_ZSD_Flash \
    libCamera_hi1634mipiraw_VSS_Capture \
    libCamera_hi1634mipiraw_Video_1080 \
    libCamera_hi1634mipiraw_Video_1080_60fps \
    libCamera_hi1634mipiraw_Video_4k \
    libCamera_hi1634mipiraw_Video_720 \
    libCamera_s5kgm2mipiraw_AI_Auto \
    libCamera_s5kgm2mipiraw_AI_Auto_HDR \
    libCamera_s5kgm2mipiraw_AI_Flower \
    libCamera_s5kgm2mipiraw_AI_Flower_HDR \
    libCamera_s5kgm2mipiraw_AI_NightView \
    libCamera_s5kgm2mipiraw_AI_NightView_4cell \
    libCamera_s5kgm2mipiraw_AI_NightView_HDR \
    libCamera_s5kgm2mipiraw_AI_NightView_Preview \
    libCamera_s5kgm2mipiraw_AI_NightView_Preview_Zoom_2x \
    libCamera_s5kgm2mipiraw_AI_NightView_Preview_Zoom_4x \
    libCamera_s5kgm2mipiraw_AI_NightView_ScaledUp \
    libCamera_s5kgm2mipiraw_AI_People \
    libCamera_s5kgm2mipiraw_AI_People_HDR \
    libCamera_s5kgm2mipiraw_AI_Sky \
    libCamera_s5kgm2mipiraw_AI_Sky_HDR \
    libCamera_s5kgm2mipiraw_AI_Snow \
    libCamera_s5kgm2mipiraw_AI_Snow_HDR \
    libCamera_s5kgm2mipiraw_AI_Text \
    libCamera_s5kgm2mipiraw_AI_Text_HDR \
    libCamera_s5kgm2mipiraw_E2EHDR_Preview \
    libCamera_s5kgm2mipiraw_E2EHDR_Video \
    libCamera_s5kgm2mipiraw_Face_Capture \
    libCamera_s5kgm2mipiraw_Face_Capture_4cell \
    libCamera_s5kgm2mipiraw_Face_Capture_ScaledUp \
    libCamera_s5kgm2mipiraw_Flash_Capture \
    libCamera_s5kgm2mipiraw_HDR_Capture \
    libCamera_s5kgm2mipiraw_HDR_Preview \
    libCamera_s5kgm2mipiraw_HDR_Video \
    libCamera_s5kgm2mipiraw_N3D_Capture \
    libCamera_s5kgm2mipiraw_N3D_Preview \
    libCamera_s5kgm2mipiraw_N3D_Video \
    libCamera_s5kgm2mipiraw_P1_YUV \
    libCamera_s5kgm2mipiraw_Panorama \
    libCamera_s5kgm2mipiraw_Scene_Capture \
    libCamera_s5kgm2mipiraw_Scene_Capture_4cell \
    libCamera_s5kgm2mipiraw_Scene_Capture_HDR \
    libCamera_s5kgm2mipiraw_Scene_Capture_ScaledUp \
    libCamera_s5kgm2mipiraw_Scene_Preview \
    libCamera_s5kgm2mipiraw_Scene_Preview_4k \
    libCamera_s5kgm2mipiraw_Scene_Preview_ZSD_Flash \
    libCamera_s5kgm2mipiraw_Scene_Preview_Zoom_2x \
    libCamera_s5kgm2mipiraw_Scene_Preview_Zoom_4x \
    libCamera_s5kgm2mipiraw_Steady_Cam_1080 \
    libCamera_s5kgm2mipiraw_Steady_Cam_720 \
    libCamera_s5kgm2mipiraw_VSS_Capture \
    libCamera_s5kgm2mipiraw_Video_1080 \
    libCamera_s5kgm2mipiraw_Video_1080_60fps \
    libCamera_s5kgm2mipiraw_Video_1080_Zoom_2x \
    libCamera_s5kgm2mipiraw_Video_1080_Zoom_4x \
    libCamera_s5kgm2mipiraw_Video_4k \
    libCamera_s5kgm2mipiraw_Video_4k_Zoom_2x \
    libCamera_s5kgm2mipiraw_Video_4k_Zoom_4x \
    libCamera_s5kgm2mipiraw_Video_720 \
    libCamera_s5kgm2mipiraw_Video_720_120fps \
    libCamera_s5kgm2mipiraw_Video_720_Zoom_2x \
    libCamera_s5kgm2mipiraw_Video_720_Zoom_4x \
    libCamera_s5kgm2mipiraw_Zoom_Capture \
    libCamera_s5kgm2mipiraw_Zoom_Capture_4cell \
    libCamera_s5kgm2mipiraw_Zoom_Capture_remosaic \
    libCamera_sl556mipiraw_E2EHDR_Preview \
    libCamera_sl556mipiraw_E2EHDR_Video \
    libCamera_sl556mipiraw_Face_Capture \
    libCamera_sl556mipiraw_Flash_Capture \
    libCamera_sl556mipiraw_HDR_Capture \
    libCamera_sl556mipiraw_HDR_Preview \
    libCamera_sl556mipiraw_HDR_Video \
    libCamera_sl556mipiraw_N3D_Capture \
    libCamera_sl556mipiraw_N3D_Preview \
    libCamera_sl556mipiraw_N3D_Video \
    libCamera_sl556mipiraw_P1_YUV \
    libCamera_sl556mipiraw_Scene_Capture \
    libCamera_sl556mipiraw_Scene_Capture_4cell \
    libCamera_sl556mipiraw_Scene_Preview \
    libCamera_sl556mipiraw_Scene_Preview_4k \
    libCamera_sl556mipiraw_Scene_Preview_ZSD_Flash \
    libCamera_sl556mipiraw_Video_1080 \
    libCamera_sl556mipiraw_Video_4k \
    libCamera_sl846mipiraw_AI_Auto \
    libCamera_sl846mipiraw_AI_Auto_HDR \
    libCamera_sl846mipiraw_AI_Flower \
    libCamera_sl846mipiraw_AI_Flower_HDR \
    libCamera_sl846mipiraw_AI_NightView \
    libCamera_sl846mipiraw_AI_NightView_HDR \
    libCamera_sl846mipiraw_AI_NightView_Preview \
    libCamera_sl846mipiraw_AI_People \
    libCamera_sl846mipiraw_AI_People_HDR \
    libCamera_sl846mipiraw_AI_Sky \
    libCamera_sl846mipiraw_AI_Sky_HDR \
    libCamera_sl846mipiraw_AI_Snow \
    libCamera_sl846mipiraw_AI_Snow_HDR \
    libCamera_sl846mipiraw_AI_Text \
    libCamera_sl846mipiraw_AI_Text_HDR \
    libCamera_sl846mipiraw_E2EHDR_Preview \
    libCamera_sl846mipiraw_E2EHDR_Video \
    libCamera_sl846mipiraw_Face_Capture \
    libCamera_sl846mipiraw_Flash_Capture \
    libCamera_sl846mipiraw_HDR_Capture \
    libCamera_sl846mipiraw_HDR_Preview \
    libCamera_sl846mipiraw_HDR_Video \
    libCamera_sl846mipiraw_N3D_Capture \
    libCamera_sl846mipiraw_N3D_Preview \
    libCamera_sl846mipiraw_N3D_Video \
    libCamera_sl846mipiraw_P1_YUV \
    libCamera_sl846mipiraw_Panorama \
    libCamera_sl846mipiraw_Scene_Capture \
    libCamera_sl846mipiraw_Scene_Capture_4cell \
    libCamera_sl846mipiraw_Scene_Capture_HDR \
    libCamera_sl846mipiraw_Scene_Preview \
    libCamera_sl846mipiraw_Scene_Preview_4k \
    libCamera_sl846mipiraw_Scene_Preview_ZSD_Flash \
    libCamera_sl846mipiraw_Steady_Cam \
    libCamera_sl846mipiraw_VSS_Capture \
    libCamera_sl846mipiraw_Video_1080 \
    libCamera_sl846mipiraw_Video_4k \
    libDR \
    libDefaultFpsActor \
    libFrameRecord \
    libNoFpsActor \
    libOpenCL \
    libRbsFlow \
    libSQLiteModule_VER_ALL \
    libSonyIMX230PdafLibrary \
    libSonyIMX230PdafLibraryWrapper \
    libSonyIMX338PdafLibrary \
    libSonyIMX338PdafLibraryWrapper \
    libSonyIMX386PdafLibrary \
    libSonyIMX386PdafLibraryWrapper \
    libSonyIMX519PdafLibrary \
    libSonyIMX519PdafLibraryWrapper \
    libTEECommon \
    libaal_cust \
    libaal_key \
    libaal_mtk \
    libaalservice \
    libadpcmdec_mtk \
    libarcsoft_beauty_picselfie \
    libarcsoft_dualcam_refocus \
    libarcsoft_picselfie_algorithm \
    libarcsoft_singlecam_portrait_lighting \
    libcam.afhal \
    libcam.arcsoftbokeh \
    libcam.chdr \
    libcam.feature_utils \
    libcam.hal3a.cctsvr \
    libcam.hal3a.log \
    libcam.hal3a.v3.ae \
    libcam.hal3a.v3.ai3a \
    libcam.hal3a.v3.awb \
    libcam.hal3a.v3.dng \
    libcam.hal3a.v3.fsmgr \
    libcam.hal3a.v3.lscMgr \
    libcam.hal3a.v3.lsctbl.50 \
    libcam.hal3a.v3.nvram.50 \
    libcam.hal3a.v3.platform \
    libcam.hal3a.v3.resultpool \
    libcam.hal3a.v3 \
    libcam.halisp.buf \
    libcam.halisp.common \
    libcam.halisp \
    libcam.halsensor.hwintegration \
    libcam.halsensor \
    libcam.iopipe \
    libcam.isptuning \
    libcam.pdtblgen \
    libcam.seninfn3d \
    libcam.tuning.cache \
    libcam.utils.sensorprovider \
    libcam.vhdr \
    libcamalgo.3dnr \
    libcamalgo.aidepth \
    libcamalgo.dngop \
    libcamalgo.eis \
    libcamalgo.fdft \
    libcamalgo.fsc \
    libcamalgo.gyro \
    libcamalgo.ispfeature \
    libcamalgo.lmv \
    libcamalgo.lsc \
    libcamalgo.nr \
    libcamalgo.platform \
    libcamalgo.platform2 \
    libcamalgo.util1 \
    libcamalgo.util2 \
    libcamalgo.utility \
    libcamalgo.vaidepth \
    libcamalgo.warp \
    libcamdrv_imem \
    libcamdrv_isp \
    libcamdrv_tuning_mgr \
    libcamdrv_twin \
    libcameracustom.eis \
    libcameracustom.plugin \
    libcameracustom \
    libccci_util \
    libcodec2_mtk_c2store \
    libcodec2_mtk_vdec \
    libcodec2_mtk_venc \
    libcodec2_soft_mtk_alacdec \
    libcodec2_soft_mtk_apedec \
    libcodec2_soft_mtk_imaadpcmdec \
    libcodec2_soft_mtk_mp3dec \
    libcodec2_soft_mtk_msadpcmdec \
    libcodec2_soft_mtk_wmadec \
    libcodec2_vpp_qt_plugin \
    libcodec2_vpp_rs_plugin \
    libcomposer_ext \
    libconnfem \
    libeffecthal.base \
    libets_trustlet \
    libfeature.face \
    libfeature.stereo.provider \
    libfeature_3dnr \
    libfeature_eis \
    libfeature_fsc \
    libfeature_lmv \
    libfeature_rss \
    libfeatureiodrv_mem \
    libforkexecwrap \
    libformatter \
    libfpfactory_v2-impl \
    libfpfactory_v2 \
    libfpsph \
    libged \
    libgpu_aux \
    libgpud \
    libgralloc_extra \
    libgralloc_metadata \
    libgralloctypes_mtk \
    libgz_gp_client \
    libgz_uree \
    libheichal \
    libicd_decoder \
    libifcutils_mtk \
    libimageio \
    libimageio_plat_drv \
    libimageio_plat_pipe \
    libkmsetkey \
    libksensor \
    liblpcnr \
    libmml \
    libmnetlink_v104 \
    libmnl \
    libmp3dec_mtk \
    libmpbase \
    libmsnr \
    libmtcloader \
    libmtk-ril \
    libmtkcam.atmseventmgr \
    libmtkcam.eventcallback \
    libmtkcam.featurepipe.capture \
    libmtkcam.featurepipe.streaming \
    libmtkcam.featurepipe.vsdof_util \
    libmtkcam.logicalmodule \
    libmtkcam_3rdparty.core \
    libmtkcam_3rdparty.customer \
    libmtkcam_3rdparty.mtk \
    libmtkcam_3rdparty \
    libmtkcam_calibration_convertor \
    libmtkcam_calibration_provider \
    libmtkcam_debugutils \
    libmtkcam_device3_app \
    libmtkcam_device3_hal \
    libmtkcam_device3_hidl \
    libmtkcam_device3_hidlutils \
    libmtkcam_device3_utils \
    libmtkcam_devicesessionpolicy \
    libmtkcam_diputils \
    libmtkcam_exif \
    libmtkcam_fdvt \
    libmtkcam_featurepolicy \
    libmtkcam_featureutils \
    libmtkcam_fwkutils \
    libmtkcam_grallocutils \
    libmtkcam_hwnode \
    libmtkcam_hwutils \
    libmtkcam_imgbuf \
    libmtkcam_mapping_mgr \
    libmtkcam_metadata \
    libmtkcam_metastore \
    libmtkcam_mfb \
    libmtkcam_modulefactory_aaa \
    libmtkcam_modulefactory_custom \
    libmtkcam_modulefactory_drv \
    libmtkcam_modulefactory_utils \
    libmtkcam_modulehelper \
    libmtkcam_pipeline \
    libmtkcam_pipeline_fbm \
    libmtkcam_pipelinemodel \
    libmtkcam_pipelinemodel_adapter \
    libmtkcam_pipelinemodel_capture \
    libmtkcam_pipelinemodel_isp \
    libmtkcam_pipelinemodel_session \
    libmtkcam_pipelinemodel_utils \
    libmtkcam_pipelinemodel_zsl \
    libmtkcam_pipelinepolicy-aov \
    libmtkcam_pipelinepolicy-security \
    libmtkcam_pipelinepolicy-smvr \
    libmtkcam_pipelinepolicy \
    libmtkcam_pipelinepolicy_factory \
    libmtkcam_prerelease \
    libmtkcam_rsc \
    libmtkcam_scenariorecorder \
    libmtkcam_stdutils \
    libmtkcam_streamutils \
    libmtkcam_synchelper \
    libmtkcam_sysutils \
    libmtkcam_tuning_utils \
    libmtkcam_ulog \
    libmtkcam_vsync_util \
    libmtkisp_metadata \
    libmtknetcap \
    libmtkrilutils \
    libmtkutils \
    libperfctl_vendor \
    libpower_timer \
    libpowerhal \
    libpowerhalwrap_vendor \
    libpq_cust_base \
    libpqframework \
    libpqparamparser \
    libratconfig \
    libremosaic_wrapper \
    libremosaiclib \
    librilfusion \
    librpc \
    libsensor_custom \
    libsensor_lge_cal \
    libsensor_lge_hd_cal \
    libstereoinfoaccessor_vsdof \
    libstorage_otp \
    libsysenv \
    libtlcWidevineModularDrm \
    libudf \
    libviagpsrpc \
    libwpfa \
    libwvhidl \
    libdrmclearkeyplugin \
    libmockdrmcryptoplugin \
    libwvdrmengine \
    libdpframework \
    libpq_prot \
    libmtkcam_streaminfo_plugin-p1stt \
    s5kgm2_mipi_raw_IdxMgr \
    s5kgm2_mipi_raw_tuning \
    sensors.mtk \
    sensors.sar-1.0 \
    sl556_mipi_raw_IdxMgr \
    sl556_mipi_raw_tuning \
    sl846_mipi_raw_IdxMgr \
    sl846_mipi_raw_tuning \
    vendor.lge.hardware.cameraex@1.0 \
    vendor.lge.hardware.lgdata@1.0 \
    vendor.lge.hardware.lgdata@1.1 \
    vendor.lge.hardware.radio@2.0 \
    vendor.mediatek.hardware.camera.atms@1.0 \
    vendor.mediatek.hardware.camera.frhandler@1.0 \
    vendor.mediatek.hardware.camera.isphal@1.0 \
    vendor.mediatek.hardware.camera.lomoeffect@1.0 \
    vendor.mediatek.hardware.camera.postproc@1.0 \
    vendor.mediatek.hardware.camera.security@1.0 \
    vendor.mediatek.hardware.composer_ext@1.0 \
    vendor.mediatek.hardware.keymaster_attestation@1.0 \
    vendor.mediatek.hardware.keymaster_attestation@1.1 \
    vendor.mediatek.hardware.mmagent@1.0 \
    vendor.mediatek.hardware.netdagent@1.0 \
    vendor.mediatek.hardware.power@2.0 \
    vendor.mediatek.hardware.pq@2.0 \
    vendor.mediatek.hardware.pq@2.1 \
    vendor.mediatek.hardware.pq@2.10 \
    vendor.mediatek.hardware.pq@2.11 \
    vendor.mediatek.hardware.pq@2.12 \
    vendor.mediatek.hardware.pq@2.13 \
    vendor.mediatek.hardware.pq@2.2 \
    vendor.mediatek.hardware.pq@2.3 \
    vendor.mediatek.hardware.pq@2.4 \
    vendor.mediatek.hardware.pq@2.5 \
    vendor.mediatek.hardware.pq@2.6 \
    vendor.mediatek.hardware.pq@2.7 \
    vendor.mediatek.hardware.pq@2.8 \
    vendor.mediatek.hardware.pq@2.9 \
    vendor.trustonic.tee.tui@1.0 \
    vendor.trustonic.tee@1.0 \
    vendor.trustonic.tee@1.1 \
    libims.lge \
    libimscamerajni.lge \
    libimsmmpf.lge \
    libimswms.lge \
    libnfc-nxp-nci.lge \
    vendor.lge.hardware.radio@2.0 \
    vendor.lge.hardware.sensors.devicecontext@1.0 \
    vendor.lge.hardware.sensors@1.0 \
    vendor.lge.hardware.sensors@1.1 \
    vendor.lge.hardware.sensors@1.2 \
    vendor.lge.hardware.vss_ims@1.0 \
    vendor.mediatek.hardware.mtkradioex@3.0 \
    gnss-mtk.xml \
    gnss@2.1-service.xml \
    manifest_android.hardware.drm@1.3-service.widevine.xml \
    ccci_mdinit \
    ccci_rpcd \
    fuelgauged \
    fuelgauged_nvram \
    gsm0710muxd \
    android.hardware.bluetooth@1.1-service-mediatek \
    android.hardware.drm@1.3-service.widevine \
    android.hardware.gnss-service.mediatek \
    android.hardware.graphics.allocator@4.0-service-mediatek \
    android.hardware.keymaster@4.1-service.trustonic \
    android.hardware.media.c2@1.2-mediatek-64b \
    android.hardware.secure_element@1.2-service-mediatek \
    android.hardware.thermal@2.0-service.mtk \
    android.hardware.usb@1.1-service-mediatekv2 \
    camerahalserver \
    mtkfusionrild \
    tetheroffloadservice \
    vendor.lge.hardware.lgdata@1.1-service \
    vendor.lge.hardware.vss_ims@1.0-service \
    vendor.mediatek.hardware.keymaster_attestation@1.1-service \
    vendor.mediatek.hardware.mms@1.6-service \
    vendor.mediatek.hardware.mtkpower@1.0-service \
    vendor.mediatek.hardware.nvram@1.1-service \
    vendor.mediatek.hardware.pq@2.2-service \
    vendor.trustonic.tee@1.1-service \
    mcDriverDaemon \
    mnld \
    mtk_agpsd \
    netdagent \
    nvram_daemon \
    rcs_volte_stack \
    thermal \
    thermal_manager \
    thermalloadalgod \
    volte_clientapi_ua \
    volte_rcs_ua \
    vpud \
    wlan_assistant

PRODUCT_PACKAGES += \
    vendor_bin_hw_android_hardware_media_c2@1_2-mediatek \
    vendor_lib_libmtk_drvb_so \
    vendor_lib64_hw_vulkan_mt6885_so \
    vendor_lib64_hw_gatekeeper_default_so \
    vendor_lib64_libdpframework_so \
    vendor_lib64_libmtk_drvb_so \
    vendor_lib64_libpq_prot_so
